[2024-02-07T01:05:08.381+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: censoEnade.cria_diretorios manual__2024-02-07T01:05:04.997456+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
