[2024-02-07T01:30:46.961+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: da.criar_tabela_db manual__2024-02-07T01:30:44.433963+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
