[2024-02-07T01:31:07.641+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagSQL.criar_tabela_db manual__2024-02-07T01:31:05.635221+00:00 [queued]>
[2024-02-07T01:31:07.656+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagSQL.criar_tabela_db manual__2024-02-07T01:31:05.635221+00:00 [queued]>
[2024-02-07T01:31:07.657+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-07T01:31:07.682+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): criar_tabela_db> on 2024-02-07 01:31:05.635221+00:00
[2024-02-07T01:31:07.692+0000] {standard_task_runner.py:60} INFO - Started process 2249 to run task
[2024-02-07T01:31:07.695+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dagSQL', 'criar_tabela_db', 'manual__2024-02-07T01:31:05.635221+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dagSQL.py', '--cfg-path', '/tmp/tmpcmn6kx2m']
[2024-02-07T01:31:07.699+0000] {standard_task_runner.py:88} INFO - Job 74: Subtask criar_tabela_db
[2024-02-07T01:31:07.773+0000] {task_command.py:423} INFO - Running <TaskInstance: dagSQL.criar_tabela_db manual__2024-02-07T01:31:05.635221+00:00 [running]> on host 113c724a1462
[2024-02-07T01:31:07.831+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'criar_tabela_db', field 'sql'. Template: 'criar_tabela_db.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2024-02-07T01:31:07.833+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: criar_tabela_db.sql
[2024-02-07T01:31:07.844+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dagSQL, task_id=criar_tabela_db, execution_date=20240207T013105, start_date=20240207T013107, end_date=20240207T013107
[2024-02-07T01:31:07.861+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 74 for task criar_tabela_db (criar_tabela_db.sql; 2249)
[2024-02-07T01:31:07.909+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-07T01:31:07.928+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
