[2024-02-06T23:48:11.608+0000] {processor.py:161} INFO - Started process (PID=3898) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:48:11.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:48:11.611+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:48:11.610+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:48:11.632+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:48:11.629+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.oprators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.oprators'
[2024-02-06T23:48:11.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:48:11.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.052 seconds
[2024-02-06T23:48:41.838+0000] {processor.py:161} INFO - Started process (PID=3954) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:48:41.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:48:41.840+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:48:41.840+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:48:41.857+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:48:41.853+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.oprators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.oprators'
[2024-02-06T23:48:41.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:48:41.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.047 seconds
[2024-02-06T23:49:12.091+0000] {processor.py:161} INFO - Started process (PID=4010) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:12.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:49:12.095+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:49:12.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:12.119+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:49:12.113+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.oprators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.oprators'
[2024-02-06T23:49:12.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:12.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.061 seconds
[2024-02-06T23:49:42.454+0000] {processor.py:161} INFO - Started process (PID=4066) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:42.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:49:42.456+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:49:42.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:42.473+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:49:42.469+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.oprators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.oprators'
[2024-02-06T23:49:42.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:42.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.046 seconds
[2024-02-06T23:49:51.975+0000] {processor.py:161} INFO - Started process (PID=4109) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:51.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:49:51.977+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:49:51.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:52.010+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:49:52.004+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 31, in <module>
    extrai_obras = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-06T23:49:52.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:49:52.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.065 seconds
[2024-02-06T23:50:22.262+0000] {processor.py:161} INFO - Started process (PID=4165) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:50:22.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:50:22.264+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:50:22.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:50:22.281+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:50:22.277+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 31, in <module>
    extrai_obras = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-06T23:50:22.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:50:22.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.047 seconds
[2024-02-06T23:50:52.701+0000] {processor.py:161} INFO - Started process (PID=4221) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:50:52.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:50:52.704+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:50:52.703+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:50:52.723+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:50:52.719+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 31, in <module>
    extrai_obras = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-06T23:50:52.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:50:52.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.049 seconds
[2024-02-06T23:51:01.785+0000] {processor.py:161} INFO - Started process (PID=4228) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:01.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:01.787+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:01.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:01.813+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:01.809+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.tcepe.operators.tcepe import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.tcepe'
[2024-02-06T23:51:01.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:01.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.055 seconds
[2024-02-06T23:51:07.155+0000] {processor.py:161} INFO - Started process (PID=4232) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:07.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:07.158+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:07.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:07.182+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:07.179+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators.tcepe import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:51:07.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:07.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.056 seconds
[2024-02-06T23:51:11.210+0000] {processor.py:161} INFO - Started process (PID=4233) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:11.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:11.213+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:11.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:11.225+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:11.223+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 5
    from airflow.utils.dates import import PythonOperator
                                    ^
SyntaxError: invalid syntax
[2024-02-06T23:51:11.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:11.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.040 seconds
[2024-02-06T23:51:12.634+0000] {processor.py:161} INFO - Started process (PID=4238) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:12.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:12.636+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:12.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:12.663+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:12.659+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators.tcepe import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:51:12.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:12.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.054 seconds
[2024-02-06T23:51:15.278+0000] {processor.py:161} INFO - Started process (PID=4248) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:15.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:15.280+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:15.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:15.292+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:15.291+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6
    from airflow.providers.operatorsimport PythonOperator
                                           ^
SyntaxError: invalid syntax
[2024-02-06T23:51:15.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:15.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.041 seconds
[2024-02-06T23:51:16.308+0000] {processor.py:161} INFO - Started process (PID=4249) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:16.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:16.310+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:16.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:16.340+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:16.335+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:51:16.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:16.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.062 seconds
[2024-02-06T23:51:18.628+0000] {processor.py:161} INFO - Started process (PID=4266) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:18.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:18.630+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:18.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:18.656+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:18.651+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:51:18.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:18.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.055 seconds
[2024-02-06T23:51:38.138+0000] {processor.py:161} INFO - Started process (PID=4293) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:38.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:38.143+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:38.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:38.164+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:38.163+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:51:38.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:38.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.058 seconds
[2024-02-06T23:51:39.178+0000] {processor.py:161} INFO - Started process (PID=4294) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:39.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:39.181+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:39.180+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:39.225+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:39.218+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 31, in <module>
    extrai_obras = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-02-06T23:51:39.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:39.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.075 seconds
[2024-02-06T23:51:41.295+0000] {processor.py:161} INFO - Started process (PID=4295) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:41.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:41.298+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:41.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:41.313+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:41.312+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6
    from airflow.providers.operatorsimport PythonOperator
                                           ^
SyntaxError: invalid syntax
[2024-02-06T23:51:41.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:41.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.045 seconds
[2024-02-06T23:51:44.478+0000] {processor.py:161} INFO - Started process (PID=4300) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:44.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:51:44.482+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:44.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:44.508+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:51:44.504+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:51:44.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:51:44.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.058 seconds
[2024-02-06T23:52:14.642+0000] {processor.py:161} INFO - Started process (PID=4356) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:14.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:52:14.644+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:14.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:14.657+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:14.654+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:52:14.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:14.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.044 seconds
[2024-02-06T23:52:29.258+0000] {processor.py:161} INFO - Started process (PID=4405) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:29.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:52:29.261+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:29.261+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:29.287+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:29.284+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:52:29.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:29.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.056 seconds
[2024-02-06T23:52:31.299+0000] {processor.py:161} INFO - Started process (PID=4406) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:31.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:52:31.301+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:31.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:31.327+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:31.323+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:52:31.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:31.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.058 seconds
[2024-02-06T23:52:34.388+0000] {processor.py:161} INFO - Started process (PID=4407) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:34.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:52:34.391+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:34.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:34.421+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:34.416+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:52:34.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:34.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.058 seconds
[2024-02-06T23:52:41.783+0000] {processor.py:161} INFO - Started process (PID=4411) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:41.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:52:41.786+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:41.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:41.817+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:52:41.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:52:41.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:52:41.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.067 seconds
[2024-02-06T23:53:12.083+0000] {processor.py:161} INFO - Started process (PID=4467) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:53:12.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:53:12.086+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:53:12.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:53:12.104+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:53:12.100+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:53:12.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:53:12.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.051 seconds
[2024-02-06T23:53:42.350+0000] {processor.py:161} INFO - Started process (PID=4523) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:53:42.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:53:42.353+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:53:42.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:53:42.370+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:53:42.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:53:42.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:53:42.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.051 seconds
[2024-02-06T23:54:12.507+0000] {processor.py:161} INFO - Started process (PID=4579) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:12.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:54:12.510+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:12.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:12.528+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:12.523+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 6, in <module>
    from airflow.providers.operators import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.operators'
[2024-02-06T23:54:12.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:12.556+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.052 seconds
[2024-02-06T23:54:14.536+0000] {processor.py:161} INFO - Started process (PID=4580) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:14.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:54:14.538+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:14.538+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:14.564+0000] {processor.py:840} INFO - DAG(s) 'censoEnade' retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:14.691+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:14.690+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:censoEnade
[2024-02-06T23:54:14.705+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:14.705+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:censoEnade
[2024-02-06T23:54:14.716+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:14.715+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:censoEnade
[2024-02-06T23:54:14.716+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:14.716+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-06T23:54:14.733+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:14.732+0000] {dag.py:3058} INFO - Creating ORM DAG for censoEnade
[2024-02-06T23:54:14.745+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:14.745+0000] {dag.py:3823} INFO - Setting next_dagrun for censoEnade to 2024-02-06 00:00:00+00:00, run_after=2024-02-07 00:00:00+00:00
[2024-02-06T23:54:14.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.246 seconds
[2024-02-06T23:54:19.482+0000] {processor.py:161} INFO - Started process (PID=4609) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:19.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:54:19.484+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:19.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:19.516+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:19.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 52, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:54:19.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:19.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.061 seconds
[2024-02-06T23:54:20.587+0000] {processor.py:161} INFO - Started process (PID=4611) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:20.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:54:20.590+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:20.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:20.613+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:20.609+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 52, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:54:20.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:20.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.057 seconds
[2024-02-06T23:54:50.850+0000] {processor.py:161} INFO - Started process (PID=4667) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:50.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:54:50.852+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:50.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:50.873+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:54:50.869+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 52, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:54:50.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:54:50.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.050 seconds
[2024-02-06T23:55:21.169+0000] {processor.py:161} INFO - Started process (PID=4723) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:55:21.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:55:21.171+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:55:21.171+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:55:21.195+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:55:21.190+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 52, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:55:21.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:55:21.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.054 seconds
[2024-02-06T23:55:51.483+0000] {processor.py:161} INFO - Started process (PID=4779) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:55:51.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:55:51.485+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:55:51.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:55:51.507+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:55:51.502+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 52, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:55:51.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:55:51.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.052 seconds
[2024-02-06T23:56:20.711+0000] {processor.py:161} INFO - Started process (PID=4829) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:20.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:56:20.713+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:20.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:20.744+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:20.740+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 44, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:56:20.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:20.769+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.060 seconds
[2024-02-06T23:56:42.383+0000] {processor.py:161} INFO - Started process (PID=4862) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:42.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:56:42.385+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:42.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:42.402+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:42.401+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:56:42.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:42.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.053 seconds
[2024-02-06T23:56:44.500+0000] {processor.py:161} INFO - Started process (PID=4863) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:44.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:56:44.503+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:44.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:44.521+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:44.520+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:56:44.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:44.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.051 seconds
[2024-02-06T23:56:48.795+0000] {processor.py:161} INFO - Started process (PID=4868) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:48.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:56:48.797+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:48.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:48.813+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:56:48.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
                   ^
SyntaxError: invalid syntax
[2024-02-06T23:56:48.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:56:48.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.048 seconds
[2024-02-06T23:57:01.359+0000] {processor.py:161} INFO - Started process (PID=4917) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:01.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:01.361+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:01.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:01.377+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:01.376+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
                   ^
SyntaxError: invalid syntax
[2024-02-06T23:57:01.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:01.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.045 seconds
[2024-02-06T23:57:06.424+0000] {processor.py:161} INFO - Started process (PID=4918) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:06.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:06.427+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:06.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:06.445+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:06.443+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
                   ^
SyntaxError: invalid syntax
[2024-02-06T23:57:06.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:06.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.049 seconds
[2024-02-06T23:57:09.496+0000] {processor.py:161} INFO - Started process (PID=4919) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:09.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:09.499+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:09.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:09.514+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:09.514+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
                   ^
SyntaxError: invalid syntax
[2024-02-06T23:57:09.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:09.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.048 seconds
[2024-02-06T23:57:26.065+0000] {processor.py:161} INFO - Started process (PID=4965) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:26.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:26.068+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:26.067+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:26.084+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:26.083+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:57:26.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:26.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.046 seconds
[2024-02-06T23:57:29.613+0000] {processor.py:161} INFO - Started process (PID=4976) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:29.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:29.615+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:29.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:29.630+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:29.629+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:57:29.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:29.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.046 seconds
[2024-02-06T23:57:44.082+0000] {processor.py:161} INFO - Started process (PID=4980) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:44.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:44.085+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:44.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:44.100+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:44.100+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:57:44.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:44.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.045 seconds
[2024-02-06T23:57:48.307+0000] {processor.py:161} INFO - Started process (PID=4985) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:48.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:48.310+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:48.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:48.325+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:48.324+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:57:48.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:48.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.046 seconds
[2024-02-06T23:57:50.038+0000] {processor.py:161} INFO - Started process (PID=4995) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:50.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:50.040+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:50.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:50.056+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:50.055+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:57:50.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:50.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.046 seconds
[2024-02-06T23:57:57.982+0000] {processor.py:161} INFO - Started process (PID=5034) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:57.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:57:57.984+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:57.983+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:57.998+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:57:57.997+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:57:57.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:57:58.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.044 seconds
[2024-02-06T23:58:06.118+0000] {processor.py:161} INFO - Started process (PID=5036) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:06.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:58:06.120+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:06.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:06.135+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:06.134+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:58:06.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:06.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.043 seconds
[2024-02-06T23:58:08.174+0000] {processor.py:161} INFO - Started process (PID=5037) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:08.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:58:08.177+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:08.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:08.192+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:08.191+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:58:08.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:08.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.044 seconds
[2024-02-06T23:58:12.289+0000] {processor.py:161} INFO - Started process (PID=5038) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:12.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:58:12.291+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:12.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:12.306+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:12.306+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:58:12.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:12.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.044 seconds
[2024-02-06T23:58:13.665+0000] {processor.py:161} INFO - Started process (PID=5042) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:13.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:58:13.668+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:13.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:13.686+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:13.685+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:58:13.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:13.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.050 seconds
[2024-02-06T23:58:15.733+0000] {processor.py:161} INFO - Started process (PID=5043) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:15.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:58:15.736+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:15.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:15.751+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:15.750+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:58:15.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:15.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.044 seconds
[2024-02-06T23:58:46.111+0000] {processor.py:161} INFO - Started process (PID=5099) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:46.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:58:46.114+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:46.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:46.129+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:58:46.128+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:58:46.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:58:46.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.042 seconds
[2024-02-06T23:59:15.075+0000] {processor.py:161} INFO - Started process (PID=5152) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:15.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:59:15.079+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:15.079+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:15.102+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:15.101+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 47
    python_callable=extrair_obras,
    ^
SyntaxError: invalid syntax
[2024-02-06T23:59:15.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:15.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.060 seconds
[2024-02-06T23:59:18.439+0000] {processor.py:161} INFO - Started process (PID=5156) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:18.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:59:18.442+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:18.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:18.475+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:18.470+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 44, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:59:18.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:18.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.066 seconds
[2024-02-06T23:59:19.704+0000] {processor.py:161} INFO - Started process (PID=5161) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:19.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:59:19.706+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:19.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:19.734+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:19.730+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 44, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:59:19.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:19.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.056 seconds
[2024-02-06T23:59:50.299+0000] {processor.py:161} INFO - Started process (PID=5217) to work on /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:50.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censoEnade.py for tasks to queue
[2024-02-06T23:59:50.301+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:50.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:50.326+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:59:50.321+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censoEnade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censoEnade.py", line 44, in <module>
    extrai_obras = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-02-06T23:59:50.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censoEnade.py
[2024-02-06T23:59:50.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censoEnade.py took 0.059 seconds
