[2024-02-06T23:28:09.921+0000] {processor.py:161} INFO - Started process (PID=1691) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:28:09.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:28:09.925+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:28:09.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:28:09.939+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:28:09.938+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 20
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:28:09.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:28:09.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.044 seconds
[2024-02-06T23:28:40.752+0000] {processor.py:161} INFO - Started process (PID=1747) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:28:40.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:28:40.755+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:28:40.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:28:40.769+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:28:40.768+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 20
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:28:40.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:28:40.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.041 seconds
[2024-02-06T23:29:11.382+0000] {processor.py:161} INFO - Started process (PID=1803) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:29:11.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:29:11.385+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:29:11.384+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:29:11.397+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:29:11.396+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 20
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:29:11.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:29:11.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.043 seconds
[2024-02-06T23:29:42.049+0000] {processor.py:161} INFO - Started process (PID=1859) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:29:42.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:29:42.053+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:29:42.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:29:42.066+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:29:42.065+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 20
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:29:42.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:29:42.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.042 seconds
[2024-02-06T23:30:12.324+0000] {processor.py:161} INFO - Started process (PID=1915) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:30:12.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:30:12.327+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:30:12.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:30:12.341+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:30:12.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 20
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:30:12.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:30:12.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.044 seconds
[2024-02-06T23:30:42.850+0000] {processor.py:161} INFO - Started process (PID=1971) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:30:42.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:30:42.854+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:30:42.853+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:30:42.864+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:30:42.863+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 20
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:30:42.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:30:42.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.041 seconds
[2024-02-06T23:31:13.447+0000] {processor.py:161} INFO - Started process (PID=2027) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:13.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:31:13.450+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:31:13.450+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:13.464+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:31:13.463+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 20
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:31:13.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:13.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:31:29.324+0000] {processor.py:161} INFO - Started process (PID=2047) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:29.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:31:29.326+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:31:29.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:29.339+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:31:29.338+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 24
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:31:29.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:29.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.044 seconds
[2024-02-06T23:31:59.917+0000] {processor.py:161} INFO - Started process (PID=2103) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:59.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:31:59.921+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:31:59.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:59.935+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:31:59.934+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 24
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:31:59.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:31:59.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.046 seconds
[2024-02-06T23:32:18.353+0000] {processor.py:161} INFO - Started process (PID=2140) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:18.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:32:18.356+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:18.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:18.369+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:18.368+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 24
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:32:18.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:18.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.042 seconds
[2024-02-06T23:32:39.832+0000] {processor.py:161} INFO - Started process (PID=2196) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:39.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:32:39.835+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:39.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:39.850+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:39.849+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 25
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:32:39.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:39.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.041 seconds
[2024-02-06T23:32:41.872+0000] {processor.py:161} INFO - Started process (PID=2197) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:41.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:32:41.875+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:41.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:41.890+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:41.889+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 6
    from
        ^
SyntaxError: invalid syntax
[2024-02-06T23:32:41.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:41.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:32:45.941+0000] {processor.py:161} INFO - Started process (PID=2198) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:45.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:32:45.944+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:45.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:45.957+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:32:45.957+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 6
    from
        ^
SyntaxError: invalid syntax
[2024-02-06T23:32:45.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:32:45.980+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.042 seconds
[2024-02-06T23:33:16.240+0000] {processor.py:161} INFO - Started process (PID=2254) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:33:16.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:33:16.243+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:33:16.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:33:16.259+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:33:16.258+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 6
    from
        ^
SyntaxError: invalid syntax
[2024-02-06T23:33:16.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:33:16.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.047 seconds
[2024-02-06T23:33:46.695+0000] {processor.py:161} INFO - Started process (PID=2310) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:33:46.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:33:46.699+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:33:46.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:33:46.714+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:33:46.713+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 6
    from
        ^
SyntaxError: invalid syntax
[2024-02-06T23:33:46.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:33:46.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.047 seconds
[2024-02-06T23:34:16.802+0000] {processor.py:161} INFO - Started process (PID=2366) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:34:16.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:34:16.806+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:34:16.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:34:16.819+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:34:16.818+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 6
    from
        ^
SyntaxError: invalid syntax
[2024-02-06T23:34:16.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:34:16.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.042 seconds
[2024-02-06T23:34:38.769+0000] {processor.py:161} INFO - Started process (PID=2412) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:34:38.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:34:38.773+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:34:38.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:34:38.788+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:34:38.787+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 24
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:34:38.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:34:38.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.052 seconds
[2024-02-06T23:35:08.982+0000] {processor.py:161} INFO - Started process (PID=2467) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:08.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:08.986+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:08.986+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:09.003+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:09.002+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 24
    cria_diretorios = BashOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:35:09.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:09.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.060 seconds
[2024-02-06T23:35:09.506+0000] {processor.py:161} INFO - Started process (PID=2469) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:09.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:09.509+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:09.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:09.522+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:09.522+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 30
    extrai_obras = TcePeOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:35:09.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:09.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.042 seconds
[2024-02-06T23:35:39.596+0000] {processor.py:161} INFO - Started process (PID=2524) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:39.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:39.599+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:39.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:39.614+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:39.614+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 5
    from air
           ^
SyntaxError: invalid syntax
[2024-02-06T23:35:39.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:39.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.053 seconds
[2024-02-06T23:35:40.702+0000] {processor.py:161} INFO - Started process (PID=2526) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:40.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:40.705+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:40.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:40.721+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:40.721+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 5
    from airflow.
                ^
SyntaxError: invalid syntax
[2024-02-06T23:35:40.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:40.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.051 seconds
[2024-02-06T23:35:43.620+0000] {processor.py:161} INFO - Started process (PID=2537) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:43.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:43.627+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:43.626+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:43.647+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:43.646+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 5
    from airflow.oprator
                       ^
SyntaxError: invalid syntax
[2024-02-06T23:35:43.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:43.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.062 seconds
[2024-02-06T23:35:47.670+0000] {processor.py:161} INFO - Started process (PID=2538) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:47.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:47.673+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:47.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:47.688+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:47.687+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 5
    from airflow.oprators.python
                               ^
SyntaxError: invalid syntax
[2024-02-06T23:35:47.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:47.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.047 seconds
[2024-02-06T23:35:49.759+0000] {processor.py:161} INFO - Started process (PID=2539) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:49.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:49.762+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:49.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:49.776+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:49.775+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 5
    from airflow.oprators.python import
                                       ^
SyntaxError: invalid syntax
[2024-02-06T23:35:49.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:49.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.047 seconds
[2024-02-06T23:35:57.887+0000] {processor.py:161} INFO - Started process (PID=2546) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:57.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:35:57.891+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:57.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:57.904+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:35:57.903+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = TcePeOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:35:57.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:35:57.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.044 seconds
[2024-02-06T23:36:02.934+0000] {processor.py:161} INFO - Started process (PID=2553) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:02.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:36:02.938+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:02.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:02.955+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:02.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:36:02.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:02.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.048 seconds
[2024-02-06T23:36:03.859+0000] {processor.py:161} INFO - Started process (PID=2561) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:03.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:36:03.865+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:03.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:03.884+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:03.883+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:36:03.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:03.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.074 seconds
[2024-02-06T23:36:22.315+0000] {processor.py:161} INFO - Started process (PID=2598) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:22.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:36:22.319+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:22.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:22.332+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:22.331+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:36:22.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:22.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.041 seconds
[2024-02-06T23:36:52.420+0000] {processor.py:161} INFO - Started process (PID=2654) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:52.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:36:52.423+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:52.423+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:52.437+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:36:52.436+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:36:52.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:36:52.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.044 seconds
[2024-02-06T23:37:22.825+0000] {processor.py:161} INFO - Started process (PID=2711) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:22.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:37:22.829+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:22.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:22.842+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:22.841+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:37:22.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:22.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:37:29.909+0000] {processor.py:161} INFO - Started process (PID=2718) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:29.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:37:29.914+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:29.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:29.929+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:29.928+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:37:29.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:29.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:37:35.899+0000] {processor.py:161} INFO - Started process (PID=2732) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:35.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:37:35.902+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:35.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:35.915+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:35.914+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:37:35.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:35.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:37:40.230+0000] {processor.py:161} INFO - Started process (PID=2754) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:40.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:37:40.232+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:40.232+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:40.246+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:40.245+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 32
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:37:40.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:40.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:37:48.243+0000] {processor.py:161} INFO - Started process (PID=2770) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:48.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:37:48.247+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:48.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:48.260+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:48.259+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 32
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:37:48.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:48.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.046 seconds
[2024-02-06T23:37:54.324+0000] {processor.py:161} INFO - Started process (PID=2777) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:54.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:37:54.327+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:54.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:54.340+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:54.339+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 1
    import apache-a
                 ^
SyntaxError: invalid syntax
[2024-02-06T23:37:54.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:54.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.042 seconds
[2024-02-06T23:37:56.369+0000] {processor.py:161} INFO - Started process (PID=2778) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:56.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:37:56.372+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:56.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:56.385+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:37:56.384+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 1
    import apache-airflow
                 ^
SyntaxError: invalid syntax
[2024-02-06T23:37:56.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:37:56.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.040 seconds
[2024-02-06T23:38:00.444+0000] {processor.py:161} INFO - Started process (PID=2779) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:00.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:38:00.446+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:38:00.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:00.458+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:38:00.458+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 32
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:38:00.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:00.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.040 seconds
[2024-02-06T23:38:03.488+0000] {processor.py:161} INFO - Started process (PID=2780) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:03.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:38:03.491+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:38:03.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:03.504+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:38:03.503+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:38:03.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:03.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.043 seconds
[2024-02-06T23:38:33.702+0000] {processor.py:161} INFO - Started process (PID=2836) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:33.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:38:33.706+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:38:33.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:33.719+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:38:33.718+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:38:33.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:38:33.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.043 seconds
[2024-02-06T23:39:03.887+0000] {processor.py:161} INFO - Started process (PID=2892) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:39:03.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:39:03.890+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:39:03.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:39:03.904+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:39:03.903+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:39:03.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:39:03.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:39:34.344+0000] {processor.py:161} INFO - Started process (PID=2948) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:39:34.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:39:34.348+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:39:34.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:39:34.362+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:39:34.361+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:39:34.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:39:34.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.047 seconds
[2024-02-06T23:40:04.779+0000] {processor.py:161} INFO - Started process (PID=3004) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:40:04.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:40:04.782+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:40:04.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:40:04.795+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:40:04.794+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:40:04.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:40:04.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.043 seconds
[2024-02-06T23:40:35.178+0000] {processor.py:161} INFO - Started process (PID=3060) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:40:35.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:40:35.181+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:40:35.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:40:35.193+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:40:35.192+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:40:35.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:40:35.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.040 seconds
[2024-02-06T23:41:05.540+0000] {processor.py:161} INFO - Started process (PID=3116) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:41:05.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:41:05.544+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:41:05.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:41:05.557+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:41:05.556+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:41:05.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:41:05.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.044 seconds
[2024-02-06T23:41:35.808+0000] {processor.py:161} INFO - Started process (PID=3172) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:41:35.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:41:35.811+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:41:35.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:41:35.825+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:41:35.824+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:41:35.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:41:35.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.048 seconds
[2024-02-06T23:42:06.287+0000] {processor.py:161} INFO - Started process (PID=3228) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:42:06.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:42:06.290+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:42:06.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:42:06.306+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:42:06.305+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:42:06.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:42:06.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.045 seconds
[2024-02-06T23:42:36.807+0000] {processor.py:161} INFO - Started process (PID=3284) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:42:36.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:42:36.811+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:42:36.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:42:36.825+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:42:36.824+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:42:36.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:42:36.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.048 seconds
[2024-02-06T23:43:07.342+0000] {processor.py:161} INFO - Started process (PID=3340) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:43:07.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:43:07.346+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:43:07.345+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:43:07.360+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:43:07.358+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:43:07.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:43:07.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.058 seconds
[2024-02-06T23:43:34.875+0000] {processor.py:161} INFO - Started process (PID=3396) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:43:34.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:43:34.880+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:43:34.879+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:43:34.892+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:43:34.891+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:43:34.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:43:34.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.051 seconds
[2024-02-06T23:44:05.151+0000] {processor.py:161} INFO - Started process (PID=3452) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:44:05.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:44:05.154+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:44:05.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:44:05.166+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:44:05.165+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:44:05.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:44:05.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.043 seconds
[2024-02-06T23:44:35.567+0000] {processor.py:161} INFO - Started process (PID=3508) to work on /opt/airflow/dags/censo_enade.py
[2024-02-06T23:44:35.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/censo_enade.py for tasks to queue
[2024-02-06T23:44:35.571+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:44:35.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:44:35.583+0000] {logging_mixin.py:188} INFO - [2024-02-06T23:44:35.582+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/censo_enade.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/censo_enade.py", line 31
    extrai_obras = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-02-06T23:44:35.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/censo_enade.py
[2024-02-06T23:44:35.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/censo_enade.py took 0.042 seconds
