[2024-02-11T00:46:32.885+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: censoEnade.select_conceito_2021 manual__2024-02-11T00:46:24.387532+00:00 [queued]>
[2024-02-11T00:46:32.897+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: censoEnade.select_conceito_2021 manual__2024-02-11T00:46:24.387532+00:00 [queued]>
[2024-02-11T00:46:32.898+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-11T00:46:32.915+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): select_conceito_2021> on 2024-02-11 00:46:24.387532+00:00
[2024-02-11T00:46:32.923+0000] {standard_task_runner.py:60} INFO - Started process 127 to run task
[2024-02-11T00:46:32.926+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'censoEnade', 'select_conceito_2021', 'manual__2024-02-11T00:46:24.387532+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/censoEnade.py', '--cfg-path', '/tmp/tmpm6mbvg9j']
[2024-02-11T00:46:32.927+0000] {standard_task_runner.py:88} INFO - Job 291: Subtask select_conceito_2021
[2024-02-11T00:46:32.987+0000] {task_command.py:423} INFO - Running <TaskInstance: censoEnade.select_conceito_2021 manual__2024-02-11T00:46:24.387532+00:00 [running]> on host 7e5b5e202339
[2024-02-11T00:46:33.091+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NÃ©fi Fernandes' AIRFLOW_CTX_DAG_ID='censoEnade' AIRFLOW_CTX_TASK_ID='select_conceito_2021' AIRFLOW_CTX_EXECUTION_DATE='2024-02-11T00:46:24.387532+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-11T00:46:24.387532+00:00'
[2024-02-11T00:46:33.098+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/censoEnade.py", line 92, in select_data_from_xlsx
    df = pd.read_excel(input_file, sheet_name=sheet_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-02-11T00:46:33.111+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=censoEnade, task_id=select_conceito_2021, execution_date=20240211T004624, start_date=20240211T004632, end_date=20240211T004633
[2024-02-11T00:46:33.129+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 291 for task select_conceito_2021 (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 127)
[2024-02-11T00:46:33.139+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-11T00:46:33.159+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
