[2024-02-09T01:23:30.279+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagSQL.criar_tabela_db scheduled__2024-02-07T00:00:00+00:00 [queued]>
[2024-02-09T01:23:30.300+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagSQL.criar_tabela_db scheduled__2024-02-07T00:00:00+00:00 [queued]>
[2024-02-09T01:23:30.301+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-09T01:23:30.332+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): criar_tabela_db> on 2024-02-07 00:00:00+00:00
[2024-02-09T01:23:30.346+0000] {standard_task_runner.py:60} INFO - Started process 75 to run task
[2024-02-09T01:23:30.353+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dagSQL', 'criar_tabela_db', 'scheduled__2024-02-07T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dagSQL.py', '--cfg-path', '/tmp/tmpighitaxv']
[2024-02-09T01:23:30.366+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask criar_tabela_db
[2024-02-09T01:23:30.503+0000] {task_command.py:423} INFO - Running <TaskInstance: dagSQL.criar_tabela_db scheduled__2024-02-07T00:00:00+00:00 [running]> on host 366ff31d219b
[2024-02-09T01:23:30.688+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NÃ©fi Fernandes' AIRFLOW_CTX_DAG_ID='dagSQL' AIRFLOW_CTX_TASK_ID='criar_tabela_db' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-07T00:00:00+00:00'
[2024-02-09T01:23:30.690+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS TB_CLIENTE(
    ID INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    dt date
)
[2024-02-09T01:23:30.706+0000] {base.py:83} INFO - Using connection ID 'postgres-***' for task execution.
[2024-02-09T01:23:30.731+0000] {base.py:83} INFO - Using connection ID 'postgres-***' for task execution.
[2024-02-09T01:23:30.756+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  database "public" does not exist

[2024-02-09T01:23:30.773+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dagSQL, task_id=criar_tabela_db, execution_date=20240207T000000, start_date=20240209T012330, end_date=20240209T012330
[2024-02-09T01:23:30.813+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 82 for task criar_tabela_db (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  database "public" does not exist
; 75)
[2024-02-09T01:23:30.851+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-09T01:23:30.890+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
