[2024-02-11T01:32:38.138+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: censoEnade.select_enade_2021 manual__2024-02-11T01:32:30.143479+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
