[2024-02-07T01:30:47.009+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: da.criar_tabela_db scheduled__2024-02-06T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
