[2024-02-10T02:12:56.727+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: censoEnade.cria_diretorios_2022 manual__2024-02-10T02:12:53.270356+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
