[2024-02-11T01:12:30.439+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: censoEnade.select_conceito_2021 manual__2024-02-11T01:12:20.829349+00:00 [queued]>
[2024-02-11T01:12:30.450+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: censoEnade.select_conceito_2021 manual__2024-02-11T01:12:20.829349+00:00 [queued]>
[2024-02-11T01:12:30.451+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-11T01:12:30.475+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): select_conceito_2021> on 2024-02-11 01:12:20.829349+00:00
[2024-02-11T01:12:30.483+0000] {standard_task_runner.py:60} INFO - Started process 253 to run task
[2024-02-11T01:12:30.485+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'censoEnade', 'select_conceito_2021', 'manual__2024-02-11T01:12:20.829349+00:00', '--job-id', '358', '--raw', '--subdir', 'DAGS_FOLDER/censoEnade.py', '--cfg-path', '/tmp/tmpvzmpn_ju']
[2024-02-11T01:12:30.487+0000] {standard_task_runner.py:88} INFO - Job 358: Subtask select_conceito_2021
[2024-02-11T01:12:30.546+0000] {task_command.py:423} INFO - Running <TaskInstance: censoEnade.select_conceito_2021 manual__2024-02-11T01:12:20.829349+00:00 [running]> on host 7e5b5e202339
[2024-02-11T01:12:30.878+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NÃ©fi Fernandes' AIRFLOW_CTX_DAG_ID='censoEnade' AIRFLOW_CTX_TASK_ID='select_conceito_2021' AIRFLOW_CTX_EXECUTION_DATE='2024-02-11T01:12:20.829349+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-11T01:12:20.829349+00:00'
[2024-02-11T01:12:33.571+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/censoEnade.py", line 95, in select_data_from_xlsx
    df.to_excel(output_file, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2252, in to_excel
    formatter.write(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 934, in write
    writer = ExcelWriter(  # type: ignore[abstract]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 60, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1219, in __init__
    self._handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'C:/***-docker/dataset/diretorio_de_selecao'
[2024-02-11T01:12:33.591+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=censoEnade, task_id=select_conceito_2021, execution_date=20240211T011220, start_date=20240211T011230, end_date=20240211T011233
[2024-02-11T01:12:33.608+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 358 for task select_conceito_2021 (Cannot save file into a non-existent directory: 'C:/***-docker/dataset/diretorio_de_selecao'; 253)
[2024-02-11T01:12:33.630+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-11T01:12:33.652+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
